/**
 * Mapping des noms d'espèces français (slug, minuscules, sans accents) vers le slug anglais PokeAPI.
 * Utilisé pour la recherche / filtre en français et pour ability-is-hidden quand l'espèce est en FR.
 */
function normalizeKey(s: string): string {
  return (s || "")
    .toLowerCase()
    .trim()
    .normalize("NFD")
    .replace(/\u0300-\u036f/g, "")
    .replace(/\s+/g, "-")
    .replace(/_/g, "-");
}

const speciesFrToEn: Record<string, string> = {
  // Gen 1
  bulbizarre: "bulbasaur",
  herbizarre: "ivysaur",
  florizarre: "venusaur",
  salamèche: "charmander",
  reptincel: "charmeleon",
  dracaufeu: "charizard",
  carapuce: "squirtle",
  carabaffe: "wartortle",
  tortank: "blastoise",
  chenipan: "caterpie",
  chrysacier: "metapod",
  papilusion: "butterfree",
  aspicot: "weedle",
  coconfort: "kakuna",
  dardargnan: "beedrill",
  roucool: "pidgey",
  roucoups: "pidgeotto",
  roucarnage: "pidgeot",
  rattata: "rattata",
  rattatac: "raticate",
  piafabec: "spearow",
  rapasdepic: "fearow",
  abo: "ekans",
  arbok: "arbok",
  pikachu: "pikachu",
  raichu: "raichu",
  sabelette: "sandshrew",
  sablaireau: "sandslash",
  nidoran: "nidoran-f",
  nidoranf: "nidoran-f",
  nidorina: "nidorina",
  nidoqueen: "nidoqueen",
  nidoranm: "nidoran-m",
  nidorino: "nidorino",
  nidoking: "nidoking",
  melofee: "clefairy",
  melodelfe: "clefable",
  goupix: "vulpix",
  feunard: "ninetales",
  rondoudou: "jigglypuff",
  grodoudou: "wigglytuff",
  nosferapti: "zubat",
  nosferalto: "golbat",
  mystherbe: "oddish",
  ortide: "gloom",
  rafflesia: "vileplume",
  paras: "paras",
  parasect: "parasect",
  mimitoss: "venonat",
  aeromite: "venomoth",
  taupiqueur: "diglett",
  triopikeur: "dugtrio",
  mimigal: "meowth",
  migalos: "persian",
  psykokwak: "psyduck",
  akwakwak: "golduck",
  ferosinge: "mankey",
  colossinge: "primeape",
  caninos: "growlithe",
  arcanin: "arcanine",
  ptitard: "poliwag",
  tetarte: "poliwhirl",
  tartard: "poliwrath",
  abra: "abra",
  kadabra: "kadabra",
  alakazam: "alakazam",
  machoc: "machop",
  machopeur: "machoke",
  machampion: "machamp",
  chetiflor: "bellsprout",
  boustiflor: "weepinbell",
  empiflor: "victreebel",
  tentacool: "tentacool",
  tentacruel: "tentacruel",
  racaillou: "geodude",
  gravalanch: "graveler",
  grolem: "golem",
  ponyta: "ponyta",
  galopa: "rapidash",
  ramoloss: "slowpoke",
  flagadoss: "slowbro",
  magneti: "magnemite",
  magneton: "magneton",
  canarticho: "farfetchd",
  doduo: "doduo",
  dodrio: "dodrio",
  otaria: "seel",
  lamantine: "dewgong",
  tadmorv: "grimer",
  grotadmorv: "muk",
  kokiyas: "shellder",
  crustabri: "cloyster",
  fantominus: "gastly",
  spectrum: "haunter",
  ectoplasma: "gengar",
  onix: "onix",
  soporifik: "drowzee",
  hypnotizeur: "hypno",
  krabby: "krabby",
  krabboss: "kingler",
  voltorbe: "voltorb",
  electrode: "electrode",
  noeunoeuf: "exeggcute",
  noadkoko: "exeggutor",
  osselait: "cubone",
  ossatueur: "marowak",
  kicklee: "hitmonlee",
  tygnon: "hitmonchan",
  excelangue: "lickitung",
  smogo: "koffing",
  smogogo: "weezing",
  rhinocorne: "rhyhorn",
  rhinoferos: "rhydon",
  leveinard: "chansey",
  saqueuede: "tangela",
  kangourex: "kangaskhan",
  hypotrempe: "horsea",
  hypocean: "seadra",
  poissirene: "goldeen",
  poissoroy: "seaking",
  stari: "staryu",
  staross: "starmie",
  mime: "mr-mime",
  inseceateur: "scyther",
  electrik: "electabuzz",
  magmar: "magmar",
  scarabrute: "pinsir",
  tauros: "tauros",
  magicarpe: "magikarp",
  leviator: "gyarados",
  lokhlass: "lapras",
  metamorph: "ditto",
  evoli: "eevee",
  aquali: "vaporeon",
  voltali: "jolteon",
  pyroli: "flareon",
  porygon: "porygon",
  amonita: "omanyte",
  amonistar: "omastar",
  kabuto: "kabuto",
  kabutops: "kabutops",
  ptera: "aerodactyl",
  ronflex: "snorlax",
  artikodin: "articuno",
  electhor: "zapdos",
  sulfura: "moltres",
  minidraco: "dratini",
  draco: "dragonair",
  dracolosse: "dragonite",
  mewtwo: "mewtwo",
  mew: "mew",
  germignon: "chikorita",
  macronium: "bayleef",
  meganium: "meganium",
  heracros: "heracross",
  gueriaigle: "skarmory",
  phanpy: "phanpy",
  donphan: "donphan",
  sneasel: "sneasel",
  flabebe: "flabebe",
  sapereau: "bunnelby",
  saperaud: "diggersby",
  pichu: "pichu",
  mentali: "espeon",
  noctali: "umbreon",
  wailmer: "wailmer",
  wailord: "wailord",
  roigada: "slowking",
};

export function getEnglishSpeciesSlug(speciesSlug: string): string | undefined {
  const key = normalizeKey(speciesSlug);
  return speciesFrToEn[key];
}

/** Retourne les slugs anglais dont le nom français contient la requête (ex. "ramo" → ["slowpoke"]). */
export function getEnglishSlugsForPartialQuery(query: string): string[] {
  const q = normalizeKey(query);
  if (!q) return [];
  const slugs = new Set<string>();
  for (const [fr, en] of Object.entries(speciesFrToEn)) {
    if (fr.includes(q)) slugs.add(en);
  }
  return Array.from(slugs);
}
